# Chapter 4: NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

In [3]:
my_arr=np.arange(1000000)
my_list=list(range(1000000))

In [6]:
%timeit my_arr2=my_arr*2

986 µs ± 27.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%timeit my_list2=my_list*2

13.8 ms ± 374 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## 4.1 The NumPy ndarray: A Multidimensional Array Object

In [8]:
data=np.array([[1.5,-0.1,3],[0,-3,6.5]])

In [9]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [10]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [11]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [12]:
data/data

C:\Users\Karim.Badr\AppData\Local\Temp\ipykernel_32080\2225509407.py:1: RuntimeWarning: invalid value encountered in divide
  data/data


array([[ 1.,  1.,  1.],
       [nan,  1.,  1.]])

In [13]:
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

### Creating ndarrays

In [15]:
data1=[6,7.5,8,0,1]

In [16]:
arr1=np.array(data1)

In [17]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [18]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2,3,2))

array([[[6.95323285e-310, 1.17132198e-311],
        [1.69121095e-306, 1.17132198e-311],
        [9.45763338e-308, 1.17132198e-311]],

       [[1.42419937e-306, 0.00000000e+000],
        [1.17132198e-311, 1.17132198e-311],
        [1.17132198e-311, 0.00000000e+000]]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.float32)
arr1.dtype
arr2.dtype

dtype('float64')

dtype('float32')

In [4]:
arr1==arr2

array([ True,  True,  True])

In [5]:
arr=np.array([1,2,3,4,5])


In [6]:
arr.dtype

dtype('int32')

In [7]:
float_arr=arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [8]:
float_arr.dtype

dtype('float64')

In [9]:
arr=np.array([3.6,-1.2,-2.6,0.5,12.9,11.2])
arr

array([ 3.6, -1.2, -2.6,  0.5, 12.9, 11.2])

In [10]:
arr.dtype

dtype('float64')

In [11]:
arr.astype(np.float32)

array([ 3.6, -1.2, -2.6,  0.5, 12.9, 11.2], dtype=float32)

In [12]:
arr.dtype

dtype('float64')

In [14]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 11])

In [17]:
numeric_strings=np.array(["1.24","-9.6","32"],dtype=np.string_)
numeric_strings
numeric_strings.dtype

array([b'1.24', b'-9.6', b'32'], dtype='|S4')

dtype('S4')

In [18]:
numeric_strings.astype(float)

array([ 1.24, -9.6 , 32.  ])

In [19]:
int_array=np.arange(10)

In [20]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
int_array.dtype

dtype('int32')

In [22]:
calibers=np.array([.22,.33,-1.57],dtype=np.float64)
calibers
calibers.dtype

array([ 0.22,  0.33, -1.57])

dtype('float64')

In [23]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
zeros_uint32=np.zeros(8,dtype="u4")

In [25]:
zeros_uint32


array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

### Arithmetic with NumPy Arrays

In [26]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [28]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
arr**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [34]:
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
arr2
arr

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [36]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[5]

5

In [38]:
arr[5:8]

array([5, 6, 7])

In [39]:
arr[5:8]=12

In [40]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [41]:
arr_slice=arr[5:8]

In [42]:
arr_slice
arr

array([12, 12, 12])

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [43]:
arr_slice[1]=12345
arr_slice
arr

array([   12, 12345,    12])

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [44]:
arr_slice[:]=64
arr_slice
arr

array([64, 64, 64])

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [46]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr2d[2]

array([7, 8, 9])

In [49]:
arr2d[2,]

array([7, 8, 9])

In [50]:
arr2d[:,2]

array([3, 6, 9])

In [51]:
arr2d[0][2]

3

In [52]:
arr2d[0,2]

3

In [53]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr3d[0].dtype

dtype('int32')

In [58]:
arr3d[0,:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
arr3d[1,:,:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [60]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [61]:
arr3d[1,1]

array([10, 11, 12])

In [62]:
arr3d[1,:,2]

array([ 9, 12])

In [63]:
old_values=arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
arr3d[0]

array([[42, 42, 42],
       [42, 42, 42]])

In [68]:
arr3d[0]=old_values

In [70]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
arr3d[1,0]

array([7, 8, 9])

In [72]:
x=arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [73]:
x[0]

array([7, 8, 9])

In [74]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [75]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [76]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
arr2d[2:]

array([[7, 8, 9]])

In [80]:
arr2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [82]:
arr2d[1,:2]

array([4, 5])

In [84]:
arr2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [85]:
lower_dim_slice=arr2d[1,:2]
lower_dim_slice.shape

(2,)

In [87]:
arr2d[:2,2]

array([3, 6])

In [88]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [93]:
arr2d[:2,2]

array([3, 6])

In [98]:
arr2d[:2,2:]

array([[3],
       [6]])

In [100]:
arr2d[:2,1:]=0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [101]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
arr2d[2]

array([7, 8, 9])

In [106]:
arr2d[2,:].shape

(3,)

In [105]:
arr2d[2:,:].shape

(1, 3)

In [107]:
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [112]:
arr2d[1,:2]

array([4, 5])

In [113]:
arr2d[1:2,:2]

array([[4, 5]])

### Boolean Indexing

In [114]:
names=np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [145]:
data=np.array([[4,7],[0,2],[-5,6],[0,0],[1,2],[-12,-4],[3,4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [116]:
names=="Bob"

array([ True, False, False,  True, False, False, False])

In [117]:
data[names=="Bob"]

array([[4, 7],
       [0, 0]])

In [118]:
data[names=="Bob",1]

array([7, 0])

In [119]:
data[names=="Bob",1:]

array([[7],
       [0]])

In [120]:
names!="Bob"

array([False,  True,  True, False,  True,  True,  True])

In [125]:
~(names=="Bob")

array([False,  True,  True, False,  True,  True,  True])

In [126]:
data[names!="Bob"]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [127]:
data[~(names=="Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [128]:
cond=names=="Bob"
cond

array([ True, False, False,  True, False, False, False])

In [130]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [131]:
mask=(names=="Bob")|(names=="Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [132]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [137]:
data<0

array([[False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True,  True],
       [False, False]])

In [139]:
data[data<0]=0

In [140]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [142]:
names!="Joe"

array([ True, False,  True,  True,  True, False, False])

In [146]:
data[names!="Joe"]=7
data

array([[  7,   7],
       [  0,   2],
       [  7,   7],
       [  7,   7],
       [  7,   7],
       [-12,  -4],
       [  3,   4]])

### Fancy Indexing

In [147]:
arr=np.zeros((8,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [150]:
for i in range(8):
    arr[i]=i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [151]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [152]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [156]:
arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [157]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [163]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [167]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [168]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [169]:
arr[[1,5,7,2],[0,3,1,2]]=0
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

### Transposing Arrays and Swapping Axes

In [170]:
arr=np.arange(15).reshape((3,5))

In [171]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [172]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [174]:
arr=np.array([[0,1,0],[1,2,-2],[6,3,2],[-1,0,-1],[1,0,1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [175]:
arr.T

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [176]:
np.dot(arr.T,arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [177]:
np.dot(arr,arr.T)

array([[ 1,  2,  3,  0,  0],
       [ 2,  9,  8,  1, -1],
       [ 3,  8, 49, -8,  8],
       [ 0,  1, -8,  2, -2],
       [ 0, -1,  8, -2,  2]])

In [179]:
arr.T@arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [180]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [181]:
arr.T

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [182]:
arr.swapaxes(0,1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [183]:
arr.swapaxes(1,0)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

## 4.2: Pseudorandom Number Generation

In [184]:
samples=np.random.standard_normal(size=(4,4))
samples

array([[ 0.7448583 ,  0.04039465,  1.44603831,  0.20587595],
       [-0.11311494,  0.71693515, -0.59866862,  1.03189696],
       [-0.10727249,  0.25989899, -0.00481101,  1.49221145],
       [ 0.3749357 ,  2.24449868,  0.5323486 , -0.52254004]])

In [185]:
from random import normalvariate

In [186]:
N=1000000

In [187]:
%timeit samples=[normalvariate (0,1) for x in range(N)]

824 ms ± 63.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [188]:
%timeit np.random.standard_normal(N)

21.3 ms ± 1.18 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [189]:
rng=np.random.default_rng(seed=12345)

In [190]:
rng

Generator(PCG64) at 0x24BFA74D2A0

In [191]:
data=rng.standard_normal((2,3))
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

## 4.3: Universal Functions: Fast Element-Wise Array Functions