# Chapter 4: NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np

In [3]:
my_arr=np.arange(1000000)
my_list=list(range(1000000))

In [6]:
%timeit my_arr2=my_arr*2

986 µs ± 27.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%timeit my_list2=my_list*2

13.8 ms ± 374 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## 4.1 The NumPy ndarray: A Multidimensional Array Object

In [8]:
data=np.array([[1.5,-0.1,3],[0,-3,6.5]])

In [9]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [10]:
data*10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [11]:
data+data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [12]:
data/data

C:\Users\Karim.Badr\AppData\Local\Temp\ipykernel_32080\2225509407.py:1: RuntimeWarning: invalid value encountered in divide
  data/data


array([[ 1.,  1.,  1.],
       [nan,  1.,  1.]])

In [13]:
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

### Creating ndarrays

In [15]:
data1=[6,7.5,8,0,1]

In [16]:
arr1=np.array(data1)

In [17]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [18]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr2.dtype

dtype('int32')

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2,3,2))

array([[[6.95323285e-310, 1.17132198e-311],
        [1.69121095e-306, 1.17132198e-311],
        [9.45763338e-308, 1.17132198e-311]],

       [[1.42419937e-306, 0.00000000e+000],
        [1.17132198e-311, 1.17132198e-311],
        [1.17132198e-311, 0.00000000e+000]]])

In [27]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays